"""empty message

Revision ID: 35124d42980f
Revises: e6892cf3951a
Create Date: 2022-06-23 16:37:54.386978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35124d42980f'
down_revision = 'e6892cf3951a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###
