"""empty message

Revision ID: 67c36baa7e17
Revises: 68e618d78ea5
Create Date: 2022-06-23 14:28:47.939997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c36baa7e17'
down_revision = '68e618d78ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranch_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('ranch_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ranch_name')
    op.drop_table('ranch')
    # ### end Alembic commands ###
