"""empty message

Revision ID: 68e618d78ea5
Revises: 84f8ed884739
Create Date: 2022-06-22 20:06:37.869659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e618d78ea5'
down_revision = '84f8ed884739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranch')
    op.add_column('comments', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'text')
    op.create_table('ranch',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ranch_pkey')
    )
    # ### end Alembic commands ###
