"""empty message

Revision ID: e6892cf3951a
Revises: 67c36baa7e17
Create Date: 2022-06-23 15:59:08.603068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6892cf3951a'
down_revision = '67c36baa7e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ranch', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('ranch', 'ranch_name')
    op.add_column('task', sa.Column('daily', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'daily')
    op.add_column('ranch', sa.Column('ranch_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ranch', 'name')
    # ### end Alembic commands ###
